name: qary

channels:
  - conda-forge  # conda-forge is higher priority than defaults in nlpia package
  - defaults  # top priority: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html#managing-channels
  # - anaconda  # bad idea: https://github.com/conda/conda/issues/9462

dependencies:
  - ConfigArgParse==1.2.2
  # - elasticsearch
  - html5lib
  # - hunspell
  # - hunspell-en
  - jupyter==1.0.0
  - lxml==4.5.0
  - pandas==1.0.3
  - pip
  - pre_commit==2.3.0
  - pyscaffold
  - pytest-cov
  - python>=3.7.6,<3.8.0
  - python-dotenv>=0.13.0,<0.14.0
  - regex==2020.4.4
  - seaborn==0.10.0
  - scipy==1.4.1
  - spacy==2.2.4
  - tqdm>=4.38.0,<5.0.0
  - watchdog

  - pip:
    - boto3==1.13.19
    - botocore==1.16.19
    - django>=3.0.7,<3.1.0
    - docutils==0.15.2
    - editdistance==0.5.3
    - elasticsearch==7.6.0
    - environment==1.0.0
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.2.5/en_core_web_md-2.2.5.tar.gz
    - gitpython==3.1.1
    - nltk==3.5
    - python-slugify==4.0.0
    - rapidfuzz==0.9.1
    - scikit-learn==0.22.2
    - tensorboardX==2.0
    - tensorflow==2.2.0
    # for recent cv models
    - torch>=1.5.0,<2.0.0
    - torchvision>=0.6.0,<1.0.0
    - scikit-image>=0.17.2,<1.0.0
    - transformers>=2.11.0,<2.12.0
    - Sphinx==3.0.3
    - recommonmark==0.6.0
    - m2r==0.2.1
    - wikipedia-api==0.5.4

