name: qary

channels:
  - conda-forge  # conda-forge is higher priority than defaults in nlpia package
  - defaults  # top priority: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html#managing-channels
  # - anaconda  # bad idea: https://github.com/conda/conda/issues/9462

dependencies:
  - ConfigArgParse==1.2.2
  # - elasticsearch
  - html5lib
  # - hunspell
  # - hunspell-en
  - jupyter==1.0.0
  - lxml==4.5.0
  - pandas==1.0.3
  - pip
  - pre_commit==2.3.0
  - pyscaffold
  - pytest-cov
  - python>=3.7.6,<3.8.0
  - python-dotenv>=0.13.0,<0.14.0
  - regex==2020.4.4
  - seaborn==0.10.0
  - scipy==1.4.1
  - spacy==2.2.4
  - tqdm>=4.38.0,<5.0.0
  - watchdog

  - pip:
    - -r scripts/requirements.txt
